export const ROUTES = {
  onboarding: 'Giới thiệu',
  login: 'Đăng nhập',
  register: 'Đăng ký',
  forgotPassword: 'Quên mật khẩu',
  notice: 'Thông báo',
  main: 'Main',
  home: 'Home',
  projectStack: 'Project Stack',
  project: 'Project',
  projectDetail: 'Project Detail',
  projectCreate: 'Create Project',
  projectCostDetail: 'Cost detail',
  projectAddUser: 'Add user to Project',
  projectUpdateUser: 'Update user from Project',
  projectAddCost: 'Add cost to Project',
  projectUpdateCost: 'Update cost From Project',
  teamStack: 'Team Stack',
  team: 'Team',
  teamDetail: 'Team Detail',
  createTeam: 'Create Team',
  memberStack: 'Member Stack',
  member: 'Member',
  memberDetail: 'Member Detail',
  createMember: 'Create Member',
  more: 'More',
  changePassword: 'Đổi mật khẩu',
  about: 'Thông tin'
};
